### PR TITLE
fix(scrolloverflow): IScroll is not defined when using bundler

### PR DESCRIPTION
**Pull request by gnuletik**
When using scrolloverflow with a bundler like `webpack` or `rollup`, I get the following error

```
IScroll is undefined
```

I import `fullpage` like this: 

```js
await import('fullpage.js/vendors/scrolloverflow')
const { default: fullpage } = await import('fullpage.js')

const myFullpage = new fullpage('.fullpage-container', {
	licenseKey: 'xxxx',
	scrollOverflow: true
});
```

This PR fix the issue

I've seen that there are two related issues.

This PR fixed the issue: https://github.com/alvarotrigo/fullPage.js/pull/3319 but it introduced another bug : https://github.com/alvarotrigo/fullPage.js/issues/3330

This PR fixes both issues.

### CODE REVIEW

**Comment by alvarotrigo** [comment]
What's wrong with the way it is done in the webpack example?
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/module_loaders/webpack-example/src/index.js

**Comment by alvarotrigo** [comment]
I'll merge it anyways, as it seems more logical to add the window object there :)

**Comment by alvarotrigo** [comment]
Thanks for that!

**Comment by gnuletik** [comment]
The example has two differences:

- Do not use dynamic import (await import() function):
This is because, I needed to do a dynamic import when my component is mounted in a SSR app to avoid loading fullPage.js on server side (where it fails as windows is not defined).

- Anonymous import (do not get the exported function):
In the example IScroll is imported but not used, so it triggers an error for ESLint.

Thanks for the merge :)

**Comment by alvarotrigo** [comment]
Thanks for the explanation! 👍

**Pull request merged**
