### PR TITLE
Bug Fix: #3392

### PR DESCRIPTION
**Pull request by dotEthan**
setAllowScrolling: false does not work with scrollBar:true.

Added else if update to ensure scrolling stopped when appropriate.

1- Make sure to commit it to the `dev` branch!
2- Read https://github.com/alvarotrigo/fullPage.js/wiki/Contributing-to-fullpage.js

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks for it! :) You finally did it!

regardin the changes (that you can also see clickong when clicking on the tab ["Files changed"](https://github.com/alvarotrigo/fullPage.js/pull/3405/files) on this same page.  You'll notice you are missing the changes on the mouseWheelHandler function [we talked about](https://github.com/alvarotrigo/fullPage.js/issues/3392#issuecomment-420003614).

**Comment by dotEthan** [comment]
Right, I wasn't clear if that was still needed after your talk with the other person. Can I add to this existing pull request or should I close it, add the changes and then do another?

**Comment by alvarotrigo** [comment]
You can add it to the existent one.

**Comment by dotEthan** [comment]
Ok, added the mousewheel scroll check.

**Comment by alvarotrigo** [comment]
Thanks for that! Merged!!
You are officially a contributor to fullpage.js! Congrats! 👍

**Comment by dotEthan** [comment]
Thanks for the help! Working on second pull request now. Hopefully a bit smoother...

**Pull request merged**
