### PR TITLE
lazyLoad: per slide

### PR DESCRIPTION
**Pull request by blueyed**
This is a first shot at addressing https://github.com/alvarotrigo/fullPage.js/issues/1337.

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks for it!
Just a couple of comments below.

**Comment by blueyed** [comment]
Thanks for your prompt response!  I'm glad you like it and that the approach seems to be good.

I've pushed a "fixup!" comment.

Please let me know if it's good like that, and I'll squash it.

I've only quickly looked into this when I've realized that it needs to be optimized, and would have expected that my attempt wouldn't be that good probably.

**Comment by blueyed** [comment]
What do you think about the idea from #1337 to pre-fetch the previous/next slide(s)?

This should be configurable as a number for the amount of surrounding items to pre-fetch, and default to `1` for next/prev, allowing for `0` to only load the current slide then.

Is this what `lazyDistance` was meant to be?
It could then apply to sections and slides maybe.

**Comment by alvarotrigo** [comment]
Thanks for it, merged.

**Comment by blueyed** [comment]
Thanks for merging it, although it was not really ready.

See #1340 for a follow-up regarding the `lazyDistance` idea.

**Pull request merged**
