### PR TITLE
adding scss stylesheet

### PR DESCRIPTION
**Pull request by Jhony0311**
A simple sass stylesheet for the plugin. Hopefully this will help to include as a bower component in many projects

### CODE REVIEW

**Comment by alvarotrigo** [comment]
I appreciate it, but I don't see the point on having the scss file here. 
This is such an small stylesheet and adding an extra file can confuse some people who lack of much web development knowledge. 

The benefits of using scss or sass are for developers and in this case it doesn't seem to make much sense to me.
The stylesheet is rarely updated and its quite easy to understand.

**Comment by Jhony0311** [comment]
I understand your point, but as I said, is easier to add this plugin as a dependency in projects if it have a scss or sass stylesheet that can be easily integrate with the project css structure. But it's your choice, Im just trying to collaborate because this plugin save me a couple of times.

**Comment by alvarotrigo** [comment]
> is easier to add this plugin as a dependency in projects if it have a scss or sass stylesheet that can be easily integrate with the project css structure.

That's interesting. Could you explain that a bit more?

**Comment by Jhony0311** [comment]
Well initially just to have the stylesheet in scss let me extend some behaviors from it or apply some behaviors to it. Then also I can make some variables so it can be easily configurable from the stylesheet or can be integrated with some mixins that developer have in their projects. Things that with just CSS can't be possible. Its awesome that this plugin have a simple and easy stylesheet but with a sass or scss integration will be more comfortable to customize it.

**Comment by valkyr-** [comment]
I usualy overwrite almost all CSS with my needs and I think many developers do this. This could be helpfull sometimes, having the SASS, you can understand the CSS easier at first look. This could be merged. My opinion :+1:

**Comment by yumyo** [comment]
+1

**Comment by kylerberry** [comment]
:thumbsup:

**Comment by alvarotrigo** [comment]
@Jhony0311 there was some changes in the CSS regarding the navigation bullets.
If you update your SCSS I'll merge it.

**Comment by Jhony0311** [comment]
I will, expect my next commit soon!

**Comment by kukac7** [comment]
:+1:

**Comment by Jhony0311** [comment]
Hey @alvarotrigo I have updated the stylesheet

**Comment by kukac7** [comment]
@Jhony0311 I think you should not prefix given, the preprocessor (or autoprefixer) do anyway.

**Comment by alvarotrigo** [comment]
@Jhony0311 any comments on that?

**Comment by Jhony0311** [comment]
Well that's something I was thinking. If @alvarotrigo will use sass as development it will be useful to set a gruntfile with task to compile and autoprefix this automatically, also we can include variables and some mixins to make it more useful to the developers who decide to use the sass stylesheet in their projects.

**Comment by alvarotrigo** [comment]
Thanks for it!

**Comment by alvarotrigo** [comment]
@Jhony0311 please look at https://github.com/alvarotrigo/fullPage.js/issues/1113 it seems the SCSS version is missing things.

**Pull request merged**
