### PR TITLE
Added new function recreate() 

### PR DESCRIPTION
**Pull request by rajjoshi22**
This pull request is in response to the issue I recently posted (issue #2075). 

Essentially, calling `$.fn.fullpage.destroy();` on the container at anytime would disable the plugin on that page permanently until refresh. 

The added function `$.fn.fullpage.recreate()`, when called, re-initializes the plugin on the page without the need to reload the page. 

The plugin is reinitialized to having all the default events handled by the plugin bound. During re-initialization, this function also defaults the values of auto scrolling and keyboard scrolling in all directions to true.

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks, but it doesn't make much sense to add an unnecessary function. 
Just placing your initialisation inside a function would do it. 

```javascript
function reCreate(){
   $('#fullpage').fullpage();
}
```

**Comment by rajjoshi22** [comment]
Hey but I _did_ try this. In the live link I provided if you navigated down to the third page I made a third button runs the above code and it didn't work. It was after trying your suggested code and having it not work in the both the latest Chrome and the latest Edge versions that I posted the issue and subsequently added the function.

**Comment by alvarotrigo** [comment]
You need to use `destroy('all')` to destroy the whole. You only destroyed the events.

**Comment by rajjoshi22** [comment]
Thanks, that clears it up. My specific use case was that I still wanted to keep the formatting but didn't need the plugin to be active at specific times.

**Pull request closed without merging**
