### PR TITLE
Bugfix #3403: autoscrolling and scrolloverflow are exclusive.

### PR DESCRIPTION
**Pull request by dotEthan**
Added an extra option to display a warning the user that autoScrolling and scrollOverflow are exclusive.

1- Make sure to commit it to the `dev` branch!
2- Read https://github.com/alvarotrigo/fullPage.js/wiki/Contributing-to-fullpage.js

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Awesome! Thanks for that @dotEthan !
Merged!

**Comment by alvarotrigo** [comment]
This time you forgot to add the issue number (#3403) on the commit title. 
When you do so, the commit appears on the related issue too, which helps to keep track of things.

**Comment by dotEthan** [comment]
Ah, that makes sense, was wondering why it didn't link over this time! Thanks again!

**Comment by alvarotrigo** [comment]
Noticed there was a bug here. It should have been `!autoScrolling`, as there are only problems when using together `scrollOverflow:true` and `autoScrolling:false`.
So I just updated it.

**Pull request merged**
