### PR TITLE
corresponding to umd

### PR DESCRIPTION
**Pull request by sugarshin**
was corresponding to UMD. please npm publish

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Can you explain a bit those changes?
I saw you removed completely the IIFE function which was passing `window `, `document`, `jQuery` and `undefined` as params. 
That was done to improve performance and compress more the size of the file.

**Comment by sugarshin** [comment]
Add params. please try.

**Comment by alvarotrigo** [comment]
Looking good. 
Need to dig in UMD to understand it a bit better, but sounds quite useful. Thanks for it!

If anybody reach this topic wondering what is this, [this explanation](http://davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/) might be useful.

**Comment by alvarotrigo** [comment]
Thanks for it!

**Comment by sugarshin** [comment]
You're welcome! by all means, please npm resister.

**Comment by alvarotrigo** [comment]
@sugarshin having troubles with it now. `publish failed PUT 500`.

**Comment by sugarshin** [comment]
@alvarotrigo Is not already registered is also of the same name? Please try to here as a reference. https://quickleft.com/blog/creating-and-publishing-a-node-js-module/

**Comment by alvarotrigo** [comment]
Still having troubles. I asked [here](https://github.com/npm/npm/issues/8047).

**Comment by alvarotrigo** [comment]
Added to npm: https://www.npmjs.com/package/fullpage.js

**Comment by sugarshin** [comment]
Thank you !

**Pull request merged**
