### PR TITLE
Added .fp-responsive-auto-height, fix for issue #1852

### PR DESCRIPTION
**Pull request by panczarny**
Fixing issue #1852

This is how it works with my changes:
http://codepen.io/panczarny/pen/mPxNyr

Adde things in .js, not in .css file.
Now just add ```.fp-responsive-auto-height ``` class to the ```.section ``` to enable its auto-height when in responsive.

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks for it! Good idea.

Although it might be easier just to add the following in the CSS stylesheet:

```css
.fp-responsive .fp-responsive-auto-height.fp-section,
.fp-responsive .fp-responsive-auto-height .fp-slide,
.fp-responsive .fp-responsive-auto-height .fp-tableCell{
    height: auto !important;
}
```

**Comment by panczarny** [comment]
I will also make adding ```.fp-responsive``` and ```.fp-responsive-auto-height``` independet, so some ```.section```s would become auto-height when fullpage is still working, e.g.
```
	$("#fullpage").fullpage({
		responsiveWidth: 750,
		responsiveAutoHeight: 1000
	});
```
But you're right, I'll take it into css.

**Comment by panczarny** [comment]
As you said I moved it to css.
Added new option called ```responsiveAutoHeightWidth``` which makes my improvement independent.
Check this out at http://codepen.io/panczarny/pen/mPxNyr.

**Comment by alvarotrigo** [comment]
Too many changes in the CSS file. The whole file changed. Make sure you use the same indentation as in the original file so I can clearly see the differences.

Regarding making responsive or responsive auto height independent doesn't make much sense to me, as usually when using `fp-auto-height` in this cases users want to create bigger sections, not smaller ones and fullpage.js won't deal properly with bigger sections than the viewport when using `autoScrolling:true`.

**Comment by alvarotrigo** [comment]
If you still planning to commit it again with the changes I mentioned let me know. 
Otherwise I'll add them by myself.

**Comment by panczarny** [comment]
Well, I didn't checked what happens if section is oversized with these functions independent. It's just like you said.
I will commit it with proper changes.

**Comment by panczarny** [comment]
Commited.
Now added is only auto-height reponsive in css and scss files. Removed my changes from JS.

**Comment by alvarotrigo** [comment]
Thanks!

**Pull request merged**
