### PR TITLE
Force string for anchor names

### PR DESCRIPTION
**Pull request by johanhermansson**
I used numbers in `data-anchor` and got an error. The `text` variable was an integer which does not have the `replace` method. I fixed it with forcing the variable to be a string.

You want it in another branch, or in another way? :)

### CODE REVIEW

**Comment by alvarotrigo** [comment]
I would use the same approach used a couple of lines above:

```javsacript
var text = String(sectionIndex);
```

Just cast it here as well:
```javascript
if(slide.length){
    text = String(text + '-' + slideAnchor);
}
```

Same branch is ok.

**Comment by alvarotrigo** [comment]
Well, in fact I would just move the existing one under the condition `if(slide.length)`:

```javascript
if(slide.length){
    text = String(text + '-' + slideAnchor);
}
var text = String(text);
```

**Comment by johanhermansson** [comment]
Ah, yes! That looks nicer! Pull request updated :)

**Comment by alvarotrigo** [comment]
Thanks for it!

**Pull request merged**
