### PR TITLE
Added slimScroll default and extending options

### PR DESCRIPTION
**Pull request by Kwaadpepper**
Slimscroll options to make fullpage more usable

### CODE REVIEW

**Comment by nylin** [comment]
Thank you @Kwaadpepper. I would really like to see this being merged into fullpage.js. I think the default options for slimscroll makes the scrollbar too fat. As of what I can see, you can't specify any global options for slimscroll, right?

**Comment by Kwaadpepper** [comment]
Please take a look at http://rocha.la/jQuery-slimScroll,
Slim scroll doesn't have global options, it runs in multiple instances.

You could try to add some prop to window and encapsulate fullpage.js
or you could just store a slimscroll object (params) in windows,

something like
```
window.fullpageSlimScrollParams = slimScroll: {
	color: '#ffcc00',
	railVisible: true,
	railColor: '#222',
	railOpacity: 0.3,
	wheelStep: 10,
	disableFadeOut: false,
}
```
and give it to fullpage like 
```
$('#fullpage').fullpage({
		verticalCentered: true,
		resize : true,
		sectionsColor : ['#ccc', '#fff'],
		anchors:['firstSlide', 'secondSlide'],
		scrollingSpeed: 700,
		easing: 'easeInQuart',
		menu: false,
		navigation: false,
		navigationPosition: 'right',
		navigationTooltips: ['firstSlide', 'secondSlide'],
		slidesNavigation: true,
		slidesNavPosition: 'bottom',
		loopBottom: false,
		loopTop: false,
		loopHorizontal: true,
		autoScrolling: true,
		scrollOverflow: false,
		css3: false,
		paddingTop: '3em',
		paddingBottom: '10px',
		normalScrollElements: '#element1, .element2',
		normalScrollElementTouchThreshold: 5,
		keyboardScrolling: true,
		touchSensitivity: 15,
		continuousVertical: false,
		animateAnchor: true,
		sectionSelector: '.section',
		slideSelector: '.slide',
		// See more options at http://rocha.la/jQuery-slimScroll @author Piotr Rochala

		slimScroll: window.fullpageSlimScrollParams,

		//events
		onLeave: function(index, nextIndex, direction){},
		afterLoad: function(anchorLink, index){},
		afterRender: function(){},
		afterResize: function(){},
		afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){},
		onSlideLeave: function(anchorLink, index, slideIndex, direction){}
	});
```
here are the full settings offslimScroll : 
```
$(selector).slimScroll({
    width: '300px',
    height: '500px',
    size: '10px',
    position: 'left',
    color: '#ffcc00',
    alwaysVisible: true,
    distance: '20px',
    start: $('#child_image_element'),
    railVisible: true,
    railColor: '#222',
    railOpacity: 0.3,
    wheelStep: 10,
    allowPageScroll: false,
    disableFadeOut: false
});
```

**Comment by alvarotrigo** [comment]
fullPage.js might change to [iScroll.js](http://cubiq.org/iscroll-5).

**Comment by andremalkine** [comment]
I know this is a hack, but I worked around it like so:

```
var oldPluginB = $.fn.pluginB;
var oldSlimScroll = $.fn.slimScroll;
$.fn.slimScroll = function( options ){
  options.wheelStep = 4;
  return oldSlimScroll.apply(this, [options] );
};
```

**Comment by Jpsy** [comment]
For the time being the "hack" of @andremalkine is just great!

**Comment by alvarotrigo** [comment]
@Kwaadpepper, would you consider updating your fullpage.js version so I can merge your PR ? 
Otherwise I'll just do it myself.

**Comment by nylin** [comment]
Hello!

 

You have a new message, please read <http://yes.com.az/summit.php?ei1v>

 

max@articstudios.se

**Comment by alvarotrigo** [comment]
@TeAmP0is0N @rodrigozamb why  are you guys even commenting on a topic that is from 2014 and that  was closed in 2016?

**Comment by jodylecompte** [comment]
Hey @alvarotrigo, I'm going to wager the same reason I ended up here just now. Via it being the top link on http://www.pullrequestroulette.com/

**Comment by alvarotrigo** [comment]
@jodylecompte that's quite weird. This pull request has been closed since 2016... while there are many others open and those won't appear on that page?

**Pull request closed without merging**
