### PR TITLE
Added new option: showActiveTooltip

### PR DESCRIPTION
**Pull request by kylerberry**
Added an option to persistently show the tooltip of the active section.

### CODE REVIEW

**Comment by kylerberry** [comment]
Can we talk about adding this? I know it needs refactoring at this point, which I'd be happy to do.

**Comment by alvarotrigo** [comment]
@kylerberry yep, we can. 
Probably it would be much easier now, you probably would only need to deal with CSS now, as the tooltip content is static at the moment.

**Comment by kylerberry** [comment]
@alvarotrigo Thanks, I'll make a PR soon

**Comment by kylerberry** [comment]
@alvarotrigo Closing this for a fresh PR since this is so old. See new PR: https://github.com/alvarotrigo/fullPage.js/pull/1081

**Pull request closed without merging**
