### PR TITLE
Bower version errors resolve.

### PR DESCRIPTION
**Pull request by usmantahirr**
I was getting jQuery version error again and again without any specific solution. So I decided to for it and change this.

### CODE REVIEW

**Comment by alvarotrigo** [comment]
I would merge this change `"jquery": "^1.x"` but not the one with jquery 2.X.
Remember that fullPage.js gives support to IE 8.

**Comment by usmantahirr** [comment]
But this creates problem when I use it with foundation or any other plugin which requires JQuery 2.x
because it throws conflict error while doing bower install

**Comment by alvarotrigo** [comment]
I guess than then we should be using `>=1.6.0` then.

**Comment by usmantahirr** [comment]
I will test it and if it works, I will send a pull request again. If it works fine at my side

**Comment by alvarotrigo** [comment]
Any news?

**Comment by alvarotrigo** [comment]
@usmantahirr did you tried it?

**Comment by usmantahirr** [comment]
Not yet. I will do it today and send a pull request again.

**Comment by alvarotrigo** [comment]
@usmantahirr what about now?
Otherwise I will just commit the changes myself.

**Comment by usmantahirr** [comment]
I am not getting any error now. Its now asking me for a JQuery version. I was getting that error on My OfficePC. Its Windows and have an older version of Node and NPM. I dont know Older versions have such issue. But now I guess this pull request isn't required.

![Image of Yaktocat]
(http://i.imgur.com/ymAXkLt.png)

**Pull request closed without merging**
