### PR TITLE
add a 'sectionAutoHeightSelector' option.

### PR DESCRIPTION
**Pull request by laomao800**
use for create some auto height section.
e.g. small footer

### CODE REVIEW

**Comment by laomao800** [comment]
<div class="section section-autoHeight" id="footer"></div>

**Comment by alvarotrigo** [comment]
Thanks for it, I'll take a look at it!

**Comment by luchorengo** [comment]
Great Work!! Thanks!!

**Comment by alvarotrigo** [comment]
I believe a much simple approach would be to just use what I recommended [here](https://github.com/alvarotrigo/fullPage.js/issues/1044#issuecomment-75812112). 

It could be integrated in fullpage.js, but it would be a much more simple change in the code. 

In any case, if sections are not full height callbacks won't fire when expected as per [this open issue](https://github.com/alvarotrigo/fullPage.js/issues/919).

**Comment by alvarotrigo** [comment]
> I believe a much simple approach would be to just use what I recommended here.

Sorry I just realized what I said doesn't make sense. The scrolling wouldn't work as expected. 

But still, I can not merge this without solving the related bug.

**Comment by alvarotrigo** [comment]
I believe I will opt for this easier solution:

```
.fp-auto-height.fp-section,
.fp-auto-height .fp-slide,
.fp-auto-height .fp-tableCell{
	height: auto !important;
}
```

And then adding this single line in the javascript side:

```
var dtop = element.hasClass('section-autoHeight') ? (dest.top - windowsHeight + element.height()) : dest.top;
```

Seems easier and requires much less changes plus it works as well for horizontal slides, which your suggestion didn't.

**Comment by alvarotrigo** [comment]
Implemented in 2.6.8.

**Pull request closed without merging**
