### PR TITLE
Bootstrap responsive visibility

### PR DESCRIPTION
**Pull request by Guilain**
Add :visible filter to move up & move down functions

### CODE REVIEW

**Comment by alvarotrigo** [comment]
That might carry other problems in other parts of the code...

**Comment by Guilain** [comment]
Like moveTo function ?

**Comment by alvarotrigo** [comment]
Yeah, for example.

Also, why is it related with bootstrap? Is it because bootstrap sets the visibility of a section to `hidden` when resizing to certain point?

I would have to review it with more time, but it can carry some problems, such as:

- If you hide the 1st section, it can be set to `active` by default on page load.
- If you hide the active section on resizing. What will happen ?
- If the active section on page load is hidden (when setting an active section/slide other than the 1st), what will happen?
- Possible problems when using `autoScrolling:false` as per [this](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L577).
- Keyboard navigation for the Home / End keys

**Comment by Guilain** [comment]
I've updated to your 2.5.9
Some problems are fixed, but it's not ready yet ...

**Comment by alvarotrigo** [comment]
@Guilain you've done something wrong. It says "2,081 additions, 2,038 deletions not shown" in your last commit.

**Pull request closed without merging**
