### PR TITLE
Fixed issue using fullPage.js + jQuery with Webpack.

### PR DESCRIPTION
**Pull request by jmgiaever**
Fixed the issue with fullPage + jQuery with Webpack. 

Initialize fullPage with jQuery like this:
```
import $ from 'jquery';
import 'fullpage.js';

$(document).ready(function() {
     $('#fullPage').fullpage({
         ...,
     });
});
```
Have tested «vanilla» too. Having troubles running all the test in `tests/`, but that's also an issue for me on the master branch and dev branch before any changes.

On dev branch I'll get this error, but have tried to roll back to 
gnome-shell-screenshot-wbh2nz
Not sure if this error is the reason why I have a problem with successfully run all tests. The browser eventually wants to kill the script.

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks for that ! I appreciate it!
I'll have to test it myself and then I'll merge it!

**Comment by jmgiaever** [comment]
Great :) Let me know if there's some issues. :)

**Comment by alvarotrigo** [comment]
Hey there! 
I was actually on holidays when you reported it, so sorry about they delay checking the issue!

Can you please specify what's the issue you were facing with webpack?

Right now, with your changes, I get `undefined` for `$.fn.fullpage`?

This is my setup:

```javascript
import $ from 'jquery';
import fullpage from './../fullpage-mod.js';    //<--- your modified fullpage

console.log("------ JS -------");
console.log(fullpage);

console.log("------ $.fn.fullpage -------");
console.log($.fn.fullpage);                  // <----------- undefined
``` 

My index.html file:
```html
<!doctype html>
<html>
  <head>
    <title>Getting Started</title>
  </head>
  <body>

    <div id="myFullpage">
        <div class="section">Section 1</div>
        <div class="section">
            <div class="slide">Slide 2.1</div>
            <div class="slide">Slide 2.2</div>
            <div class="slide">Slide 2.3</div>
        </div>
        <div class="section">Section 3</div>
    </div>

    <script src="main.js"></script>
  </body>
</html>
```

To create main.js I place myself on the root folder and run `npx webpack`.

Am I doing anything wrong?

**Comment by alvarotrigo** [comment]
The only way I managed to solve it was to change on the jQuery adapter [line 3851](https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js#L3851) the following:

```javascript
(function ($, fullpage) {
```

For this:

```javascript
(function(global, factory) {
    'use strict';
    if (typeof define === 'function' && define.amd) {
        console.log("jQuery: using ADM...");
        define(['jquery', 'fullpage.js'], function($, fullpage) {
          return factory($, fullpage, global, global.document, global.Math);
        });
    } else if (typeof exports === "object" && exports) {
        console.log("jQuery: using common js...");
        module.exports = factory(require('jquery'), require('fullpage.js'), global, global.document, global.Math);
    } else {
        console.warn("jQuery: using window object");
        factory(jQuery, fullpage, global, global.document, global.Math);
    }
})(typeof window !== 'undefined' ? window : this, function($, fullpage, window, document, Math, undefined) {
```

**Pull request closed without merging**
