### PR TITLE
Fixes #3613

### LINKED ISSUE #3613: Multiple Menus
### Description
In the [change from v2.* to v3.*](https://github.com/alvarotrigo/fullPage.js/commit/27f4f8ec22435ce01e73de7ee75395b5d42e9698) there was a regression in the code. In v2.* when providing a selector for the menu options you could provide a class selector and it would target all matched elements, in v3.* it will only target the first matched element.

### Link to isolated reproduction with no external CSS / JS
[Functionality in v2.6.6](https://codepen.io/englishtom/full/OGVoMo)
[Functionality in v3.0.4](https://codepen.io/englishtom/full/pBJZMm)

### Steps to reproduce it
1. Scroll down the page in both provided examples
2. In v2.6.6 both menu's active state are updated
3. In v3.0.4 only the first menu's active state is updated

### Versions 
All browsers
All operating systems
fullpage.js v3.0.4

### PR DESCRIPTION
**Pull request by englishtom**
**Description**
In the change from v2.* to v3.* there was a regression in the code. In v2.* when providing a selector for the menu options you could provide a class selector and it would target all matched elements, in v3.* it will only target the first matched element.

**Link to isolated reproduction with no external CSS / JS**
Functionality in v2.6.6
Functionality in v3.0.4

**This PR Contains**
Passing QUnit tests describing the missing functionality
Updates to `styleMenu` and `activateMenuElement` functions to make them deal with multiple menus rather than just grabbing the first matched element from the given selector

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Looking great! Thanks for that! 👍 
I commented a couple of things in the code.

Can you do those changes I suggested before a couple of hours?
I'm planning to release the next version now :)

**Comment by englishtom** [comment]
Hey Alvaro,

I can definitely take a look at this now, can you point me towards your comments as I don't see any commits?

Thanks,

Tom

**Comment by alvarotrigo** [comment]
Why looking again in the DOM using `$(options.menu)[i]` ? 
Just use `domElement`.

```js
$body.appendChild(domElement);
```

**Comment by alvarotrigo** [comment]
Thanks! I've merged it and modified a couple of variables!

**Pull request merged**
