### PR TITLE
- reponsive parameter can be a function which returns true or false

### PR DESCRIPTION
**Pull request by cemd**

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Explain yourself and why its necessary.

**Comment by cemd** [comment]
In a project I needed to check not only the width but also the height of the viewport. Instead of adding another option I've added the ability to declare a function. The feature is also in another similar jQuery Plugin and I found it useful.

**Comment by alvarotrigo** [comment]
The [responsive height](https://github.com/alvarotrigo/fullPage.js/issues/1256) option is a proposed enhancement. 

Checking the `height` inside the plugin initialization doesn't seem very reasonable. It wouldn't work on viewport resizing. 

It seems to me adding a function  `setResponsive(boolean)` can be more useful for that. 
This way you would be able to apply whenever you want (on mobile phone, under certain condition...)

**Comment by cemd** [comment]
The height is not checked during initialization process, but everytime the plugin checks if it should go in responsive mode, the function is called (if provided). In there, I can finely adjust when I want the plugin to go responsive and when not. And it works on viewport resizing – I use it just like that in production. 

Check the responsive-Example, I've edited it to clarify the use of a function for this use case (however, I've only read the width as in the original one).

But: A `setResponsive` function seems also useful to me.

**Comment by alvarotrigo** [comment]
> The height is not checked during initialization process, but everytime the plugin checks if it should go in responsive mode, the function is called (if provided)

Right. My mistake :D I don't know what was I thinking about.

The only problem I see with this method, although it seems useful, is that people with a basic knowledge of javascript might have troubles using it.

I see the `setResponsive` a more useful and versatile function to add.

**Comment by alvarotrigo** [comment]
Now that I think about it, there's no need to create the `setResponsive` option, as basically is the same as `setAutoScrolling`. The only difference is that hides the vertical navigation bullets.

**Pull request closed without merging**
