### PR TITLE
fix for IE11

### PR DESCRIPTION
**Pull request by panther7**

### CODE REVIEW

**Comment by alvarotrigo** [comment]
You will have to be more specific with the problem you are fixing. 

[The demo page](http://alvarotrigo.com/fullPage/) works as expected in IE 11.

**Comment by alvarotrigo** [comment]
That's not enough. 
You didn't provide any way of reproducing it and it is not clear what are you trying to solve. 

As I said previously:

> @panther7 provide an isolated reproduction of the issue and specify which device and browser you are using.

**Comment by panther7** [comment]
#1727

**Comment by alvarotrigo** [comment]
I'll close it as I see no need for it.

**Pull request closed without merging**
