### PR TITLE
Added background-color hack to dectect hover state on page load.

### PR DESCRIPTION
**Pull request by jnettik**
Detects hover over a slimScroll area on pageload. It uses the CSS hack found at http://stackoverflow.com/a/6593995/1547641. I'm including the unminified version of the same slimScroll.js for clearity. My changes start at line 250.

This is discussed in rochal/jQuery-slimScroll#133

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Testing it a bit more it doesn't seem to solve the problem. Still have troubles sometimes.
I'm testing it with srollable content on the 2nd section, and it enters in the condition you created always, not only when its on the 2nd section.

Even when the hover event is not beeing applied as you can see [in this example](http://jsfiddle.net/u9P87/13/) I made with your modification.

**Comment by jnettik** [comment]
What browsers and OS are you testing on? I'm using the modification in a project I'm working on so far without issue. Even the JSFiddle you linked to seems to be working for me.

**Comment by alvarotrigo** [comment]
The JSFiddle I posted shows that the hover is fired even when the mouse is not really over the scrollable area. 
Which means it is always true, and you can even notice the CSS style for :hover is not even in there and still acting the same way.

**Comment by alvarotrigo** [comment]
Using Chrome in Windows 7 and Mac Yosemite.

**Comment by jnettik** [comment]
Ah I see now. Looks like the default value for `background-color` in CSS is `transparent`. That is why this is always true. http://www.w3schools.com/cssref/pr_background-color.asp That throws a wrench in this. I just tested with a more noticeable color and even CSS, at least in Chrome on Yosemite, doesn't detect hover on page load.

Which means the we're back to choosing between not being able to scroll until mouse movement, or not being able to use `overflow: scroll;` on regions outside of slimScroll.js.

**Comment by jnettik** [comment]
Looking into some of the other scrolling JavaScript plugins, they don't seem to have this issue. You've already mentioned you were considering iScroll, which is one I tested that seems to work. It does seem like using a different plugin is the better long term solution to this.

**Comment by dalla777** [comment]
I'm unsure if this issue was solved at one point, but my fix for this was to manually call a mouseover. In the afterSectionLoads function, I simply added `v.element.find('.fp-scrollable').mouseover();` and that seems to have done the trick for me.

**Comment by alvarotrigo** [comment]
@dalla777 great solution! Thanks for sharing it! I'll add it in the next release!

**Comment by alvarotrigo** [comment]
Added in the latest version 2.6.5.

**Pull request closed without merging**
