### PR TITLE
Build tasks for compiling SCSS & compressing CSS and JS files

### PR DESCRIPTION
**Pull request by d13**
A high-level description of changes made:
- added Gulp and Gulp plugins
- updated the SCSS styles to match the styles in the CSS file
- added the `dist` directory to unobtrusively write the minified files and source-maps

Addresses: #1558 & #1096

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks for it @d13! Looks good!
Although, not sure why you made that many changes in the CSS file. It seems like you changed the order. Why? Oh, and the indentation as well. 

I saw you also changed the absolute links to relative ones in the documentation such as this one:
````
(https://github.com/alvarotrigo/fullPage.js#introduction)
```
Could you revert those changes as well? Keeping them absolute helps in case some sites copy the readme content into theirs or even for sites such as npmjs which extracts the docs from github. I prefer them to always link to the github docs.

If you revert those last changes and the CSS ones I'll merge it.  Feel free to create a new pull request for clarify.

**Comment by alvarotrigo** [comment]
fullpage.js 2.7.4 has just been released. You'll probably have to update your copy now before commiting it again.

**Comment by d13** [comment]
Merged and reverted style changes.

The only CSS change I kept was the change of the copyright comment from `/**` to `/*!` so the compression tool will preserve that comment.

**Comment by alvarotrigo** [comment]
Thanks a lot!

**Comment by alvarotrigo** [comment]
@d13 I'm not used to work with sass or scss but there's something wrong on the gulp file.

You said in the read me

>// Only compile the SCSS
>gulp scss

But `gulp sass` is what its required instead.
Not quite sure what are you doing there though.

**Comment by d13** [comment]
The mistake is in the documentation, I should have written `sass` as the task name as that is technically what is being compiled. `.scss` is just the file extension for SASS.

**Comment by d13** [comment]
I'll push a fix for this shortly.

**Comment by alvarotrigo** [comment]
@d13 what are you really doing with the SCSS file? Compiling it to `.css`?

In that case we should better get rid of it, as I usually work directly on the CSS file. I have the SCSS for other developers who might be interested in playing with it.

**Comment by d13** [comment]
@alvarotrigo - Yes, the `sass` task compiles the SCSS to `.css`. If you're providing a SCSS file, you should provide the means to build it in the way you expect the final CSS to look. 

What I suggest as middle ground is to remove not run in the default task and just have the developer run the sass task manually before running the compression tasks.

**Comment by alvarotrigo** [comment]
Yep, removing it from the global task should do it as I wouldn't personally use it.

**Pull request merged**
