### PR TITLE
probe version of scrolloverflow.js

### PR DESCRIPTION
**Pull request by nnmrts**
This file is a merge of the customized scrolloverflow.js and iscroll-probe.js to also allow the precise "scroll" event from iScroll. More info: [http://iscrolljs.com/#custom-events](http://iscrolljs.com/#custom-events)

### CODE REVIEW

**Comment by nnmrts** [comment]
Oh, sorry, I think I used the `master` version of your scrolloverflow.js to make this new file. Arghh. 🤕

**Comment by alvarotrigo** [comment]
> This file is a merge of the customized scrolloverflow.js and iscroll-probe.js 

What do you mean by that? 
Did you fix the issues in iScroll Probe as I did on the customized iScroll ? Could you provide more details about it ?

**Comment by nnmrts** [comment]
For me the event `scroll` wasn't available in Fullpage.js. That's a feature only available in the iScroll scroll-probe.js edition and as far as I know, you used the normal edition to create your customized iScroll edition. So I first took your customized scrolloverflow.js and added the probe feature from the scroll-probe.js file. I don't know what you mean with:

> Did you fix the issues in iScroll Probe as I did on the customized iScroll?

I mean, I didn't change your customized iScroll file itself, so your fixes are still there.

**Comment by alvarotrigo** [comment]
> That's a feature only available in the iScroll scroll-probe.js edition and as far as I know, you used the normal edition to create your customized iScroll edition. 

The iScroll version used in fullPage.js is a customization of the iScroll official version. There were [some bugs in the official version](https://github.com/cubiq/iscroll/issues/1041) that were preventing it to work as expected, and as far as I know they never got solved because the project is kind of inactive. 
I guess you didn't apply those changes?

> I mean, I didn't change your customized iScroll file itself, so your fixes are still there.

Yeah, I get that, although I would prefer to only have a single scrolloverflow.js file instead of two. 
Makes things easier.

**Pull request closed without merging**
