### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by rodriguez-alex**
I've updated the fullpage.js to use window.innerheight, and have created a check to see when the page has stopped moving to ensure it's only called once. I have tested this out in Iphone 6+, Samsung S6, Nexus 6. Here's the URL:

http://test2.forgedpixels.net/examples/normalScroll.html

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks for it @rodriguez-alex, although I'm not yet totally convince about it.
If you try to scroll up or down while the sections are about to resize, then the scrolling won't take place  and some glitches will appear.

**Comment by rodriguez-alex** [comment]
What do you mean?

My end goal is to get window.innerHeight in there, lol. I do like the extra built in functionality to make sure it fits the screen though :)  Had to do some thinking for sure.

**Comment by alvarotrigo** [comment]
> What do you mean?

Try to scroll up or down just when the resize is about to take place. You'll see the scroll won't take place and the user will be forced to stay in the same section until the resize has finished.

**Comment by rodriguez-alex** [comment]
We can clear the timeout when they're scrolling if the rebuild is the issue. Is this what you mean?

**Comment by alvarotrigo** [comment]
It shouldn't interrupt the user input.

**Comment by rodriguez-alex** [comment]
I've updated the demo with the new changes, looks good now :dancers:

**Comment by DomenicRoti** [comment]
Hey, I just tried this out and didn't see any problems, any chance we roll this in?  Thanks

**Comment by alvarotrigo** [comment]
@DomenicRoti chances are, but I still need to take a look at it with more calm. It won't be merged before January.

**Comment by alvarotrigo** [comment]
I'll close the PR temporally.

**Comment by rodriguez-alex** [comment]
Hey @alvarotrigo any updates on this? Do we see a merge anytime soon? Thanks in advance.

**Comment by alvarotrigo** [comment]
Probably for the next release. 
Could you please update it to avoid conflicts with the current version 2.7.7 ?

**Comment by alvarotrigo** [comment]
And get rid of the `normalScroll.html` file, it doesn't need to be modified to test it as far as I understood.

**Comment by rodriguez-alex** [comment]
I will update it today.

**Pull request closed without merging**
