### PR TITLE
Made lazy loading optional to prevent conflict with other lazy loadin…

### PR DESCRIPTION
**Pull request by publicJorn**
We were already using another lazy loading solution (blazy) which has some more options. Unfortunately it also uses `data-src`. So I made the fullPage.js's lazy load optional.

### CODE REVIEW

**Comment by publicJorn** [comment]
Hmm seems my editor cleaned up some more than intended. I personally don't mind, but on request I can delete it, or put it in a separate commit

**Comment by alvarotrigo** [comment]
Thanks for reporting it and for proposing a solution for it!
I suggest using a more descriptive option, such as `lazyLoading` :) 

I'll check it with more calm and merge it later on.

**Comment by alvarotrigo** [comment]
Oh, btw, needs an update to match 2.8.7

**Comment by alvarotrigo** [comment]
Let me know if you plan to do it, or I'll do it for the next release.

**Comment by publicJorn** [comment]
Been a bit busy, I'll update it later today. thanks

**Comment by publicJorn** [comment]
Hi @alvarotrigo, the conflicts are resolved. Thanks for accepting the pull request!

**Comment by alvarotrigo** [comment]
Thanks for it!

**Pull request merged**
