### PR TITLE
Adding touch event listeners for "normalScrollElements"

### PR DESCRIPTION
**Pull request by toulatip8**
Fix to issue #2664 

- *Library version*: 2.9.4.

- *Issue*: 
    - iframes are not recognized correctly as "normalScrollElements" during touch events, as they don't propagate touch events within them.

- *Proposed solution*: 
    - add explicit `touchstart` and `touchend` listeners to "normalScrollElements" 
    - disable general scrolling on `touchstart` event (instead of disabling only mouse wheel scrolling)
    - re-enable general scrolling on `touchend` event

- *Proposed changes*:
    - edit fil jquery.fullPage.js [lines 604 to 620]

```
/**
* Applying normalScroll elements.
* Ignoring the scrolls over the specified selectors.
*/
if(options.normalScrollElements){
    $document.on('mouseenter touchstart', options.normalScrollElements, function () {
        setAllowScrolling(false);
    });

    $document.on('mouseleave touchend', options.normalScrollElements, function(){
        setAllowScrolling(true);
    });
}
```

### CODE REVIEW

**Comment by alvarotrigo** [comment]
I don't see any file being changed :D 
Make sure to update your copy to the latest version, then make your changes and commit them to the branch. You should see the differences and the number of files changed under the "Files changed" tab next to the "Conversation one". Just like in this PR: https://github.com/alvarotrigo/fullPage.js/pull/2652

**Comment by alvarotrigo** [comment]
Aren't you planning to submit the pull request again? 
This one was empty :D

**Comment by toulatip8** [comment]
...I admit I tried to no avail as I'm a total git noob T-T

I read we should push to dev branch, but I'm stuck when, after editing the needed file, I (supposedly) need to `git push origin dev`. I can't seem to find `origin dev` (and as I'm lost I don't even know if it's the right thing to do, I've been following https://yangsu.github.io/pull-request-tutorial/, it's my first time ever using git, sorry T-T)

**Comment by alvarotrigo** [comment]
@toulatip8 an easy wan can be editing the file through github directly, just here:
https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js

On the top right icon to edit.

**Comment by toulatip8** [comment]
...it was easier than expected, this way. Many thanks Alvaro! :D

**Pull request merged**
