### PR TITLE
Master

### PR DESCRIPTION
**Pull request by oimken**
Fixed: Scroll failing when first section be set to auto height（after
scroll down to other section,  can not scrolling up to first section,
first section will not be display again . ）

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks for it! 

Two things:

- Convert it to this function:
```javascript
        function getDestinationTop(dest, element){
            //auto height? Scrolling only a bit, the next element's height. 
            if(element.hasClass(AUTO_HEIGHT) && dest.top){
                return dest.top - windowsHeight + element.height();
            }

            //Otherwise the whole viewport.
            return dest.top;
        }
```

And get it like this:
```javascript
var dtop = getDestinationTop(dest, element);
```

- And commit it to the `dev` branch instead.

**Comment by alvarotrigo** [comment]
Or you can even it it in a single line:

```javascript
var dtop = element.hasClass(AUTO_HEIGHT) && dest.top ? (dest.top - windowsHeight + element.height()) : dest.top;
```

**Comment by alvarotrigo** [comment]
Why did you close it?

**Comment by oimken** [comment]
sorry for closed it. I am not a professional coder.  and not  familiar with github ... really sorry for that. I will do better next time :)

**Pull request closed without merging**
