### PR TITLE
Ranjit git patch 1

### PR DESCRIPTION
**Pull request by ranjit-git**
patch for bug https://www.huntr.dev/bounties/08d2a6d0-772f-4b05-834e-86343f263c35/

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Awesome, thanks for this! 👍

**Review by alvarotrigo — APPROVED** [review]

**Comment by ranjit-git** [comment]
@alvarotrigo 
Can you plz Mark the report as valid in [huntr](https://www.huntr.dev/bounties/08d2a6d0-772f-4b05-834e-86343f263c35/)  and confirm the fix

**Comment by alvarotrigo** [comment]
Sure! Done!
Will merge it on the master branch today or tomorrow.

**Comment by ranjit-git** [comment]
@alvarotrigo  thanks for fixing the bug

**Pull request merged**
