### PR TITLE
Moves scrollOverflow code to separate handler object

### PR DESCRIPTION
**Pull request by rmarscher**
This update adds a new option called 'scrollOverflowHandler'
which consolidates all code related to scrollOverflow and
allows it to be swapped out with different functionality.

By default, it will use the existing jquery.slimScroll handling
of scroll overflow.

This should make it easier for users to either customize the
slimScroll handling or replace it with other code just as wrapping
content in a div with `overflow: scroll` or utilizing iscroll.js
as requested in issues #506, #612 and others.

### CODE REVIEW

**Comment by rmarscher** [comment]
Created a [gist](https://gist.github.com/rmarscher/5f3a62b960f5f903a6af) with a potential alternative iscroll-based handler for scrollOverflow.

**Comment by alvarotrigo** [comment]
Thanks for it!!
Looks like we have some beautiful code out there! :)

I'll take a deeper look at it, maybe not that much as a way to expect other developers to create their own handler, but more as a way to allow them to choose between using iScroll.js or slimScroll.js. (or even use a fallback for IE < 10 if slimScroll.js is present)

**Comment by rmarscher** [comment]
Thanks, @alvarotrigo! I'm sure maintaining this library is a lot of work. I hope this helps.

**Comment by alvarotrigo** [comment]
Hi @rmarscher, can you please create a new branch with it? 
I'll merge it there to keep working on other features for the next release.

**Comment by alvarotrigo** [comment]
If you can remove the hidden file `.editorconfig` from it, that'd good.

**Comment by alvarotrigo** [comment]
If you can remove the hidden file `.editorconfig` from it, that'd good.

**Comment by rmarscher** [comment]
Hi @alvarotrigo - sorry it took me a few days to respond. I removed the .editorconfig file from the project. But I would recommend adding it as it helps contributors preserve your line endings and indent-style.

I don't think I have permission to create a new branch in this repo. I think you would need to create and push the branch. Then I can close this pull request and submit a new one against that branch. Let me know once that has been done. Thanks!

**Comment by alvarotrigo** [comment]
> But I would recommend adding it as it helps contributors preserve your line endings and indent-style.

Ok, feel free to add it again. 

> Let me know once that has been done.

Done. Its called `dev`

**Comment by alvarotrigo** [comment]
I'll be adding new commits into the branch these days, you might need to update your copy before commiting it again if it finds conflicts.

**Comment by alvarotrigo** [comment]
I will probably commit the current branch today or tomorrow. 
If you still want to commit the changes then that'd probably be for 2 releases ahead. 

If you just don't have time for the merging let me know and I'll add the changes by myself.

**Comment by rmarscher** [comment]
Closing. Re-submitted against the dev branch in #1543. Thanks.

**Pull request closed without merging**
