### PR TITLE
optimized use of variables

### PR DESCRIPTION
**Pull request by tudor-sv**
Optimized use of variables. Freed  up 1kb :)

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks for it. 
The options variable is only present 3 times in the current minified version, so there's no need to change it.

If you can commit another pull request with only the changes in the other variables, that'd be nice.

**Comment by alvarotrigo** [comment]
Oh wait, now that I think about it. We only need the `$.fn.fullpage` substitution. 

The other can be achieved like this:
```javascript
(function($, window, document) {
    $.fn.fullpage = function(options) {
    };
})(jQuery, window, document);
```

**Comment by tudor-sv** [comment]
True, great suggestion !
Also added Math as a parameter (it appeared 14 times before in the minified version)

**Comment by alvarotrigo** [comment]
Thanks for it!

**Comment by tudor-sv** [comment]
my pleasure

**Pull request merged**
