### PR TITLE
Proofread and update Japanese docs

### PR DESCRIPTION
**Pull request by hoqqun**
Hola!, Alvaro Trigo-san,

I have proofread and updated the Japanese docs.

Here are the details of what I have done:

### README.doc
1. Compared with the English README.doc and added missing method descriptions such as methods  (lines [629-925](https://github.com/alvarotrigo/fullPage.js/pull/4642/files#diff-61ec3c8061cf07a99766abcb0151e3e6beef1dfa465918599f22a4972a967fecR629-R925)).
2. Corrected the layout of the README.doc as it was slightly disrupted.
3. Modified the table of contents links to point to the Japanese doc.

### how-to-activation
1. Changed the activation-key specification section of how-to-activate from Spanish to English to make it understandable for Japanese users.

### parallax
1. Made some text revisions regarding the parallax section.

### website/jp.yml
1. Corrected the website/jp.yml file to make the Japanese translation more natural.

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Awesome, thank you so much, @hoqqun ! 👍

**Comment by alvarotrigo** [comment]
@hoqqun I noticed some texts didn't get translated into Japanese. Is it intentional?
For example these two:

> Easy!: Easy!
Touch me!: Touch me!

As a reference, you can see them on the landing page on the section 3 and 4.
https://alvarotrigo.com/fullPage/

**Comment by alvarotrigo** [comment]
You can also see the current result within your translation here:
https://alvarotrigo.com/fullPage/ja/

**Comment by hoqqun** [comment]
@alvarotrigo 

Yes, these are intentional.
I left the title in English because it felt slightly awkward when translated into Japanese.

**Comment by hoqqun** [comment]
@alvarotrigo 
Also, I noticed some slight awkwardness in the wording on the website.
A period is automatically added at the end of the sentence, so it looks like a double period in Japanese.

As a Japanese speaker, I can read the text without any issues. However, it feels slightly unnatural, so if possible, it might be better to correct it.

image

**Comment by alvarotrigo** [comment]
Ok thanks for the info!

> A period is automatically added at the end of the sentence, so it looks like a double period in Japanese.

Fixed! 👍

**Pull request merged**
