### PR TITLE
A little trouble when using fullPage.js with AMD (Require.js)

### PR DESCRIPTION
**Pull request by spalax**
When i use fullpage.js with require.js window.load event triggers before fullpage has registered handler for scrollToAnchor. So i resolved this issue by checking for document.readyState, and it is helps.

### CODE REVIEW

**Comment by alvarotrigo** [comment]
I'll take a look at it in a few days.

**Comment by alvarotrigo** [comment]
It seems to me that this will fire the scrollToAnchor function when the site is not yet loaded:

```javascript
if (document.readyState != "complete") {
    $window.on('load', scrollToAnchor);
}
```

**Comment by alvarotrigo** [comment]
@spalax anything to comment on my last answer ?

**Comment by spalax** [comment]
@alvarotrigo sorry, it is a bit strange, because, if you will load your script synchronously at the html body i guess this condition will be (document.readyState != "complete") true alway. But if you require(fullpage.js) asynchronously it is mean that sometimes, fullpage.js might be required after LOAD event fired.

**Comment by alvarotrigo** [comment]
The solution doesn't seem to be simple.
Check this answer: http://stackoverflow.com/q/31308059/1081396

**Comment by alvarotrigo** [comment]
I would argue that it doesn't make much sense to load fullpage.js dynamically as it is necessary for the correct visualization of the page in any case.

**Comment by spalax** [comment]
You might controll loading manually, so if you show loading image which is playing until all async libs are loaded. In my opinion it is not a good practice to control such a thing inside library exclusively.  
IMO scrollToAnchor should be possible to run manually and of course i guess it is a trouble if your library execution logic depends on the loading order =(((

**Comment by spalax** [comment]
IMO It is a bit brakes Separation of Concerns ...

**Comment by alvarotrigo** [comment]
I believe this got solved by this PR: https://github.com/alvarotrigo/fullPage.js/pull/1982

**Pull request closed without merging**
